apiVersion: v1
kind: Service
metadata:
  name: promart
  namespace: zeus
  labels:
    zeus-application: promart
spec:
  ports:
  - port: 8080
    name: promart
  type: ClusterIP
  selector:
    app: promart
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: promart
  namespace: zeus
spec:
  serviceName: "promart"
  replicas: 1
  template:
    metadata:
      labels:
        zeus-application: promart
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: promart
          image: promartio/promart:1.0.1
          ports:
            - containerPort: 8080
              name: promart
          volumeMounts:
            - name: root
              mountPath: /usr/local/tomcat/dirigible
          env:
            - name: DIRIGIBLE_DATABASE_PROVIDER
              value: "local"
            - name: DIRIGIBLE_HOME_URL
              value: "/services/v3/web/promart/"
            - name: DIRIGIBLE_THEME_DEFAULT
              value: "florence"
            - name: KEYCLOAK_CONFIDENTIAL_PORT
              value: "443"
            - name: KEYCLOAK_SSL_REQUIRED
              value: "none"
            - name: KEYCLOAK_CLIENT_ID
              value: "platform"
            - name: KEYCLOAK_REALM
              value: "ProMART-Platform"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "https://auth.ingress.dev.promart.shoot.canary.k8s-hana.ondemand.com/auth"
      serviceAccountName: promart
  volumeClaimTemplates:
    - metadata:
        name: root
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
  name: promart
  namespace: zeus
spec:
  tls:
  - hosts:
    - promart.ingress.dev.promart.shoot.canary.k8s-hana.ondemand.com
    secretName: promart-certificate
  rules:
    - host: promart.ingress.dev.promart.shoot.canary.k8s-hana.ondemand.com
      http:
        paths:
          - path: /
            backend:
              serviceName: promart
              servicePort: 8080
